/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CTDPPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// i18n.ts
var en = {
  // General
  "CTDP Dashboard": "CTDP Dashboard",
  "No Task Selected": "No Task Selected",
  "Go to Settings": "Go to Settings to create tasks.",
  // Stats
  "Main Chain": "Main Chain",
  "Bookings": "Bookings",
  "Precedents": "Precedents",
  "Exceptions": "Exceptions",
  // Timer States
  "READY": "READY",
  "IDLE": "IDLE",
  "BOOKED": "BOOKED",
  "ACTIVE": "ACTIVE",
  "PAUSED": "PAUSED",
  // Controls
  "Book Session": "Book Session",
  "Cancel Booking": "Cancel Booking",
  "Start Session": "Start Session",
  "Skip Booking": "Skip Booking",
  "Give Up": "Give Up",
  "Pause": "Pause",
  "Resume": "Resume",
  // Modals & Confirmations
  "Reset Chain?": "This will reset chain counts and delete all exception rules. Continue?",
  "Reset All": "Reset All",
  "Cancel": "Cancel",
  "Delete Task": "Delete Task",
  "Delete": "Delete",
  "Edit Task": "Edit Task",
  "New Task": "New Task",
  "Name": "Name",
  "Description": "Description",
  "Session Duration": "Session Duration (mins)",
  "Booking Duration": "Booking Duration (mins)",
  "Save": "Save",
  "Name required": "Name required",
  // Precedents
  "Interrupt Session": "Interrupt Session",
  "Select Exception": "Select an allowed precedent to pause.",
  "New Exception Rule": "New Exception Rule",
  "Add Rule": "Add Rule",
  "Create & Use": "Create & Use",
  "Reason": "Reason",
  "Limit (mins)": "Limit (mins)",
  "No exceptions defined": "No exceptions defined.",
  "Manage Exceptions": "Manage Exceptions",
  "Delete rule": "Delete rule",
  "e.g. Bathroom": "e.g. Bathroom",
  "Why?": "Why?",
  // Settings
  "Task Chains": "Task Chains",
  "Manage chains": "Manage your different chains here.",
  "General": "General",
  "Language": "Language",
  "System Default": "System Default",
  "Enable System Notifications": "Enable System Notifications",
  "Notifications Desc": "Show desktop notifications for events.",
  "Daily Logging": "Daily Logging",
  "Date Format": "Date Format",
  "Format Desc": "e.g. YYYY-MM-DD",
  "Daily Note Folder": "Daily Note Folder",
  "Folder Desc": "Path to your daily notes folder.",
  "Auto-detect": "Auto-detect from Daily Notes Plugin",
  "Settings Updated": "Settings Updated",
  "Daily Notes plugin not found or not configured": "Daily Notes plugin not found or not configured",
  "Show Timer in Status Bar": "Show Timer in Status Bar",
  "Danger Zone": "Danger Zone",
  "Reset All Settings": "Reset All Settings",
  "Reset Desc": "WARNING: This will delete all your tasks and chains.",
  "Reset Confirm Body": "Are you sure you want to reset everything? This cannot be undone.",
  "Reset": "Reset",
  // Notifications
  "Sacred Seat Started!": "Sacred Seat Started!",
  "Session Started Body": `Time's up! Session for "{0}" started.`,
  "Session Complete!": "Session Complete!",
  "Session Complete Body": '+1 Node for "{0}".',
  "Pause Limit Exceeded!": "Pause Limit Exceeded!",
  "Pause Limit Body": 'Too long on break for "{0}". Chain Reset.',
  "Logged to Daily Note": "Logged to Daily Note"
};
var zh = {
  // General
  "CTDP Dashboard": "CTDP \u63A7\u5236\u53F0",
  "No Task Selected": "\u672A\u9009\u62E9\u4EFB\u52A1",
  "Go to Settings": "\u8BF7\u524D\u5F80\u8BBE\u7F6E\u521B\u5EFA\u4EFB\u52A1\u3002",
  // Stats
  "Main Chain": "\u4E3B\u94FE\u8282\u70B9",
  "Bookings": "\u9884\u7EA6\u6B21\u6570",
  "Precedents": "\u4F8B\u5916\u6B21\u6570",
  "Exceptions": "\u4F8B\u5916\u89C4\u5219",
  // Timer States
  "READY": "\u5C31\u7EEA",
  "IDLE": "\u7A7A\u95F2",
  "BOOKED": "\u5DF2\u9884\u7EA6",
  "ACTIVE": "\u4E13\u6CE8\u4E2D",
  "PAUSED": "\u6682\u505C\u4E2D",
  // Controls
  "Book Session": "\u9884\u7EA6\u4E13\u6CE8",
  "Cancel Booking": "\u53D6\u6D88\u9884\u7EA6",
  "Start Session": "\u5F00\u59CB\u4E13\u6CE8",
  "Skip Booking": "\u8DF3\u8FC7\u9884\u7EA6",
  "Give Up": "\u653E\u5F03/\u91CD\u7F6E",
  "Pause": "\u6682\u505C",
  "Resume": "\u6062\u590D",
  // Modals & Confirmations
  "Reset Chain?": "\u8FD9\u5C06\u91CD\u7F6E\u94FE\u8BA1\u6570\u5E76\u5220\u9664\u6240\u6709\u4F8B\u5916\u89C4\u5219\u3002\u786E\u5B9A\u7EE7\u7EED\u5417\uFF1F",
  "Reset All": "\u91CD\u7F6E\u6240\u6709",
  "Cancel": "\u53D6\u6D88",
  "Delete Task": "\u5220\u9664\u4EFB\u52A1",
  "Delete": "\u5220\u9664",
  "Edit Task": "\u7F16\u8F91\u4EFB\u52A1",
  "New Task": "\u65B0\u5EFA\u4EFB\u52A1",
  "Name": "\u540D\u79F0",
  "Description": "\u63CF\u8FF0",
  "Session Duration": "\u4E13\u6CE8\u65F6\u957F (\u5206\u949F)",
  "Booking Duration": "\u9884\u7EA6\u65F6\u957F (\u5206\u949F)",
  "Save": "\u4FDD\u5B58",
  "Name required": "\u8BF7\u8F93\u5165\u540D\u79F0",
  // Precedents
  "Interrupt Session": "\u4E2D\u65AD\u4E13\u6CE8",
  "Select Exception": "\u9009\u62E9\u4E00\u4E2A\u300C\u4E0B\u5FC5\u4E3A\u4F8B\u300D\u89C4\u5219\u4EE5\u6682\u505C\u3002",
  "New Exception Rule": "\u65B0\u5EFA\u300C\u4E0B\u5FC5\u4E3A\u4F8B\u300D\u89C4\u5219",
  "Add Rule": "\u6DFB\u52A0\u89C4\u5219",
  "Create & Use": "\u521B\u5EFA\u5E76\u4F7F\u7528",
  "Reason": "\u7406\u7531",
  "Limit (mins)": "\u65F6\u9650 (\u5206\u949F)",
  "No exceptions defined": "\u6682\u65E0\u4F8B\u5916\u89C4\u5219\u3002",
  "Manage Exceptions": "\u7BA1\u7406\u4F8B\u5916\u89C4\u5219",
  "Delete rule": "\u5220\u9664\u89C4\u5219",
  "e.g. Bathroom": "\u4F8B\u5982\uFF1A\u4E0A\u5395\u6240",
  "Why?": "\u539F\u56E0\uFF1F",
  // Settings
  "Task Chains": "\u4EFB\u52A1\u94FE\u7BA1\u7406",
  "Manage chains": "\u5728\u8FD9\u91CC\u7BA1\u7406\u4F60\u7684\u4E0D\u540C\u4EFB\u52A1\u94FE\u3002",
  "General": "\u901A\u7528\u8BBE\u7F6E",
  "Language": "\u8BED\u8A00 (Language)",
  "System Default": "\u8DDF\u968F\u7CFB\u7EDF",
  "Enable System Notifications": "\u5F00\u542F\u7CFB\u7EDF\u901A\u77E5",
  "Notifications Desc": "\u5728\u684C\u9762\u663E\u793A\u5B8C\u6210\u6216\u5931\u8D25\u7684\u901A\u77E5\u3002",
  "Daily Logging": "\u65E5\u8BB0\u8BB0\u5F55",
  "Date Format": "\u65E5\u671F\u683C\u5F0F",
  "Format Desc": "\u4F8B\u5982\uFF1AYYYY-MM-DD \u6216 YYYY\u5E74MM\u6708DD\u65E5",
  "Daily Note Folder": "\u65E5\u8BB0\u6587\u4EF6\u5939",
  "Folder Desc": "\u6BCF\u65E5\u65E5\u8BB0\u6240\u5728\u7684\u6587\u4EF6\u5939\u8DEF\u5F84\u3002",
  "Auto-detect": "\u4ECE\u300C\u65E5\u8BB0\u300D\u63D2\u4EF6\u81EA\u52A8\u83B7\u53D6\u914D\u7F6E",
  "Settings Updated": "\u8BBE\u7F6E\u5DF2\u66F4\u65B0",
  "Daily Notes plugin not found or not configured": "\u672A\u627E\u5230\u300C\u65E5\u8BB0\u300D\u63D2\u4EF6\u6216\u5176\u672A\u914D\u7F6E",
  "Show Timer in Status Bar": "\u5728\u5E95\u90E8\u72B6\u6001\u680F\u663E\u793A\u5012\u8BA1\u65F6",
  "Danger Zone": "\u5371\u9669\u533A\u57DF",
  "Reset All Settings": "\u91CD\u7F6E\u6240\u6709\u8BBE\u7F6E",
  "Reset Desc": "\u8B66\u544A\uFF1A\u8FD9\u5C06\u5220\u9664\u60A8\u7684\u6240\u6709\u4EFB\u52A1\u548C\u8BB0\u5F55\u3002",
  "Reset Confirm Body": "\u60A8\u786E\u5B9A\u8981\u91CD\u7F6E\u6240\u6709\u6570\u636E\u5417\uFF1F\u6B64\u64CD\u4F5C\u65E0\u6CD5\u64A4\u9500\u3002",
  "Reset": "\u91CD\u7F6E",
  // Notifications
  "Sacred Seat Started!": "\u795E\u5723\u5EA7\u4F4D\u5DF2\u5F00\u542F\uFF01",
  "Session Started Body": "\u65F6\u95F4\u5230\uFF01\u300C{0}\u300D\u4E13\u6CE8\u65F6\u6BB5\u81EA\u52A8\u5F00\u59CB\u3002",
  "Session Complete!": "\u4E13\u6CE8\u5B8C\u6210\uFF01",
  "Session Complete Body": "\u300C{0}\u300D\u4E3B\u94FE\u8282\u70B9 +1\u3002",
  "Pause Limit Exceeded!": "\u4F11\u606F\u8D85\u65F6\uFF01",
  "Pause Limit Body": "\u300C{0}\u300D\u4F11\u606F\u65F6\u95F4\u8FC7\u957F\uFF0C\u4EFB\u52A1\u94FE\u5DF2\u65AD\u88C2\u3002",
  "Logged to Daily Note": "\u5DF2\u8BB0\u5F55\u5230\u6BCF\u65E5\u65E5\u8BB0"
};
var resources = {
  en,
  zh
};
function t(key, lang = "en") {
  let dict = resources.en;
  if (lang === "zh")
    dict = resources.zh;
  return dict[key] || resources.en[key] || key;
}

// main.ts
var CURRENT_SETTINGS_VERSION = 1;
var DEFAULT_SETTINGS = {
  version: CURRENT_SETTINGS_VERSION,
  tasks: [],
  activeTaskId: null,
  enableNotifications: true,
  language: "system",
  dailyLogFormat: "YYYY-MM-DD",
  dailyLogFolder: "",
  enableStatusBarTimer: true
};
var VIEW_TYPE_CTDP = "ctdp-view";
var CTDPPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    if (!this.settings.activeTaskId && this.settings.tasks.length > 0) {
      this.settings.activeTaskId = this.settings.tasks[0].id;
      await this.saveSettings();
    }
    if (this.settings.dailyLogFormat === "YYYY-MM-DD" && this.settings.dailyLogFolder === "") {
      try {
        const dailyNotesPlugin = this.app.internalPlugins.getPluginById("daily-notes");
        if (dailyNotesPlugin && dailyNotesPlugin.instance && dailyNotesPlugin.instance.options) {
          this.settings.dailyLogFormat = dailyNotesPlugin.instance.options.format || "YYYY-MM-DD";
          this.settings.dailyLogFolder = dailyNotesPlugin.instance.options.folder || "";
          await this.saveSettings();
        }
      } catch (e) {
      }
    }
    this.statusBarItem = this.addStatusBarItem();
    this.registerView(VIEW_TYPE_CTDP, (leaf) => new CTDPView(leaf, this));
    this.addRibbonIcon("target", "CTDP Dashboard", () => {
      this.activateView();
    });
    this.addCommand({ id: "open-ctdp-view", name: "Open Dashboard", callback: () => {
      this.activateView();
    } });
    this.addSettingTab(new CTDPSettingTab(this.app, this));
    this.checkInterval = window.setInterval(() => {
      this.checkTimers().catch(() => {
      });
    }, 1e3);
  }
  async onunload() {
    window.clearInterval(this.checkInterval);
  }
  getLang() {
    if (this.settings.language !== "system")
      return this.settings.language;
    const locale = import_obsidian.moment.locale();
    if (locale.startsWith("zh"))
      return "zh";
    return "en";
  }
  tr(key, ...args) {
    let str = t(key, this.getLang());
    args.forEach((arg, i) => {
      str = str.replace(`{${i}}`, arg);
    });
    return str;
  }
  async checkTimers() {
    let dirty = false;
    const now = Date.now();
    if (!this.settings.tasks)
      return;
    let statusBarText = "";
    const activeTaskId = this.settings.activeTaskId;
    let viewNeedsRefresh = false;
    for (const task of this.settings.tasks) {
      if (!task.logPrecedents)
        task.logPrecedents = [];
      const oldState = task.state;
      const oldSessionStart = task.sessionStartTime;
      if (task.state === "BOOKED" && task.bookingStartTime) {
        if (now - task.bookingStartTime >= task.bookingDuration * 60 * 1e3) {
          task.auxChainCount++;
          task.state = "ACTIVE";
          task.sessionStartTime = Date.now();
          task.bookingStartTime = null;
          task.pauseStartTime = null;
          task.activePrecedentId = null;
          this.notify(this.tr("Sacred Seat Started!"), this.tr("Session Started Body", task.name));
          dirty = true;
          viewNeedsRefresh = true;
        }
      }
      if (task.state === "ACTIVE" && task.sessionStartTime) {
        if (now - task.sessionStartTime >= task.sessionDuration * 60 * 1e3) {
          await this.logToDailyNote(task);
          task.mainChainCount++;
          task.state = "IDLE";
          task.sessionStartTime = null;
          task.logBookingStartTime = null;
          task.logPrecedents = [];
          this.notify(this.tr("Session Complete!"), this.tr("Session Complete Body", task.name));
          dirty = true;
          viewNeedsRefresh = true;
        }
      }
      if (task.state === "PAUSED" && task.pauseStartTime && task.activePrecedentId) {
        const p = task.precedents.find((pr) => pr.id === task.activePrecedentId);
        if (p && now - task.pauseStartTime >= p.autoFailMinutes * 60 * 1e3) {
          this.notify(this.tr("Pause Limit Exceeded!"), this.tr("Pause Limit Body", task.name));
          this.failChainInternal(task);
          dirty = true;
          viewNeedsRefresh = true;
        }
      }
      if (task.state !== oldState)
        viewNeedsRefresh = true;
      if (this.settings.enableStatusBarTimer && task.id === activeTaskId) {
        if (task.state === "ACTIVE" && task.sessionStartTime) {
          statusBarText = `\u{1F3AF} ${this.formatTime(task.sessionDuration * 6e4 - (now - task.sessionStartTime))}`;
        } else if (task.state === "BOOKED" && task.bookingStartTime) {
          statusBarText = `\u{1F5D3}\uFE0F ${this.formatTime(task.bookingDuration * 6e4 - (now - task.bookingStartTime))}`;
        } else if (task.state === "PAUSED" && task.pauseStartTime && task.activePrecedentId) {
          const p = task.precedents.find((pr) => pr.id === task.activePrecedentId);
          if (p)
            statusBarText = `\u23F8\uFE0F ${this.formatTime(p.autoFailMinutes * 6e4 - (now - task.pauseStartTime))}`;
        }
      }
    }
    if (this.statusBarItem) {
      this.statusBarItem.setText(statusBarText);
      this.statusBarItem.style.display = statusBarText ? "inline-block" : "none";
    }
    if (dirty)
      await this.saveSettings();
    if (viewNeedsRefresh)
      this.refreshView();
  }
  refreshView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_CTDP);
    leaves.forEach((leaf) => {
      if (leaf.view instanceof CTDPView)
        leaf.view.render();
    });
  }
  notify(title, body) {
    new import_obsidian.Notice(`${title}
${body}`);
    if (this.settings.enableNotifications && Notification.permission === "granted")
      new Notification(title, { body });
  }
  formatTime(ms) {
    if (ms < 0)
      ms = 0;
    const totalSeconds = Math.ceil(ms / 1e3);
    const m = Math.floor(totalSeconds / 60);
    const s = totalSeconds % 60;
    return `${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loaded);
    await this.migrateSettings();
    if (!this.settings.tasks) {
      this.settings.tasks = [];
    }
    this.settings.tasks.forEach((t2) => {
      if (!t2.logPrecedents)
        t2.logPrecedents = [];
      if (t2.logBookingStartTime === void 0)
        t2.logBookingStartTime = null;
    });
  }
  async migrateSettings() {
    const currentVersion = this.settings.version || 0;
    let needsSave = false;
    if (currentVersion < 1) {
      if (this.settings.tasks) {
        this.settings.tasks.forEach((t2) => {
          if (t2.logPrecedents === void 0)
            t2.logPrecedents = [];
          if (t2.logBookingStartTime === void 0)
            t2.logBookingStartTime = null;
        });
      }
      this.settings.version = 1;
      needsSave = true;
    }
    if (needsSave) {
      await this.saveData(this.settings);
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getTask(id) {
    return this.settings.tasks ? this.settings.tasks.find((t2) => t2.id === id) : void 0;
  }
  async bookSession(taskId) {
    const t2 = this.getTask(taskId);
    if (!t2)
      return;
    if (t2.bookingDuration <= 0) {
      await this.startSession(taskId);
      return;
    }
    t2.state = "BOOKED";
    t2.bookingStartTime = Date.now();
    t2.logBookingStartTime = t2.bookingStartTime;
    t2.logPrecedents = [];
    await this.saveSettings();
    this.refreshView();
  }
  async startSession(taskId) {
    const t2 = this.getTask(taskId);
    if (!t2)
      return;
    if (t2.state === "BOOKED") {
      t2.auxChainCount++;
    }
    t2.state = "ACTIVE";
    t2.sessionStartTime = Date.now();
    if (!t2.logBookingStartTime && t2.bookingStartTime) {
      t2.logBookingStartTime = t2.bookingStartTime;
    }
    t2.bookingStartTime = null;
    await this.saveSettings();
    this.refreshView();
  }
  async pauseSession(taskId, pid) {
    const t2 = this.getTask(taskId);
    if (!t2)
      return;
    const p = t2.precedents.find((pr) => pr.id === pid);
    if (!p)
      return;
    t2.state = "PAUSED";
    t2.pauseStartTime = Date.now();
    t2.activePrecedentId = pid;
    p.usageCount++;
    if (!t2.logPrecedents) {
      t2.logPrecedents = [];
    }
    t2.logPrecedents.push(p.name);
    await this.saveSettings();
    this.refreshView();
  }
  async resumeSession(taskId) {
    const t2 = this.getTask(taskId);
    if (!t2)
      return;
    if (t2.pauseStartTime && t2.sessionStartTime) {
      t2.sessionStartTime += Date.now() - t2.pauseStartTime;
    }
    t2.state = "ACTIVE";
    t2.pauseStartTime = null;
    t2.activePrecedentId = null;
    await this.saveSettings();
    this.refreshView();
  }
  async completeSession(taskId) {
    const t2 = this.getTask(taskId);
    if (!t2)
      return;
    await this.logToDailyNote(t2);
    t2.mainChainCount++;
    t2.state = "IDLE";
    t2.sessionStartTime = null;
    t2.logBookingStartTime = null;
    t2.logPrecedents = [];
    await this.saveSettings();
    this.refreshView();
  }
  async failChain(taskId) {
    const t2 = this.getTask(taskId);
    if (!t2)
      return;
    this.failChainInternal(t2);
    await this.saveSettings();
    this.refreshView();
  }
  failChainInternal(t2) {
    t2.state = "IDLE";
    t2.mainChainCount = 0;
    t2.auxChainCount = 0;
    t2.precedents = [];
    t2.sessionStartTime = null;
    t2.bookingStartTime = null;
    t2.pauseStartTime = null;
    t2.activePrecedentId = null;
    t2.logBookingStartTime = null;
    t2.logPrecedents = [];
  }
  async logToDailyNote(task) {
    var _a;
    try {
      const now = (0, import_obsidian.moment)();
      const logLine = `- [x] ${(0, import_obsidian.moment)(task.sessionStartTime).format("HH:mm")} - ${now.format("HH:mm")} \u{1F3AF} **${task.name}** (\u23F0 Booked: ${task.logBookingStartTime ? (0, import_obsidian.moment)(task.logBookingStartTime).format("HH:mm") : "Direct"}${((_a = task.logPrecedents) == null ? void 0 : _a.length) > 0 ? ", \u23F8\uFE0F Exceptions: " + task.logPrecedents.join(", ") : ""})`;
      const folder = this.settings.dailyLogFolder || "";
      const format = this.settings.dailyLogFormat || "YYYY-MM-DD";
      const fileName = now.format(format);
      const pathWithExt = fileName.endsWith(".md") ? fileName : `${fileName}.md`;
      const fullPath = folder ? `${folder}/${pathWithExt}` : pathWithExt;
      const normalizedPath = (0, import_obsidian.normalizePath)(fullPath);
      let file = this.app.vault.getAbstractFileByPath(normalizedPath);
      if (!file) {
        if (folder)
          await this.ensureFolderExists(folder);
        file = await this.app.vault.create(normalizedPath, "");
      }
      if (file instanceof import_obsidian.TFile) {
        await this.app.vault.process(file, (data) => {
          const prefix = data.length > 0 && !data.endsWith("\n") ? "\n" : "";
          return data + prefix + logLine;
        });
        new import_obsidian.Notice(this.tr("Logged to Daily Note"));
      }
    } catch (e) {
      new import_obsidian.Notice("CTDP: Log failed");
    }
  }
  async ensureFolderExists(path) {
    const dirs = path.replace(/\\/g, "/").split("/");
    let current = "";
    for (const dir of dirs) {
      if (!dir)
        continue;
      current = current ? `${current}/${dir}` : dir;
      const loaded = this.app.vault.getAbstractFileByPath(current);
      if (!loaded) {
        await this.app.vault.createFolder(current);
      }
    }
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_CTDP);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (!leaf) {
        leaf = workspace.getLeaf("tab");
      }
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE_CTDP, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    } else {
      new import_obsidian.Notice("CTDP: Failed to open dashboard");
    }
  }
};
var CTDPView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CTDP;
  }
  getDisplayText() {
    return this.plugin.tr("CTDP Dashboard");
  }
  getIcon() {
    return "target";
  }
  async onOpen() {
    this.render();
    this.timerInterval = window.setInterval(() => {
      this.updateTimers();
    }, 100);
  }
  async onClose() {
    window.clearInterval(this.timerInterval);
  }
  getActiveTask() {
    if (!this.plugin.settings.activeTaskId)
      return null;
    return this.plugin.settings.tasks.find((t2) => t2.id === this.plugin.settings.activeTaskId) || null;
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("ctdp-container");
    const nav = container.createDiv("ctdp-nav");
    const taskSelect = new import_obsidian.DropdownComponent(nav);
    taskSelect.selectEl.addClass("ctdp-task-select");
    const tasks = this.plugin.settings.tasks;
    if (tasks.length === 0) {
      taskSelect.addOption("none", this.plugin.tr("No Task Selected"));
      taskSelect.setValue("none");
    } else {
      tasks.forEach((t2) => taskSelect.addOption(t2.id, t2.name));
      if (this.plugin.settings.activeTaskId && tasks.find((t2) => t2.id === this.plugin.settings.activeTaskId)) {
        taskSelect.setValue(this.plugin.settings.activeTaskId);
      } else if (tasks.length > 0) {
        taskSelect.setValue(tasks[0].id);
      }
    }
    taskSelect.onChange(async (value) => {
      if (value !== "none") {
        this.plugin.settings.activeTaskId = value;
        await this.plugin.saveSettings();
        this.render();
      }
    });
    const settingsBtn = nav.createEl("button", { cls: "ctdp-nav-icon-btn" });
    (0, import_obsidian.setIcon)(settingsBtn, "settings");
    settingsBtn.onclick = () => {
      this.plugin.app.setting.open();
      this.plugin.app.setting.openTabById(this.plugin.manifest.id);
    };
    const content = container.createDiv("ctdp-content");
    const activeTask = this.getActiveTask();
    if (!activeTask) {
      const empty = content.createDiv("ctdp-empty-state");
      empty.createEl("div", { text: "\u{1F3AF}", attr: { style: "font-size: 3em; margin-bottom: 20px;" } });
      empty.createEl("h3", { text: this.plugin.tr("No Task Selected") });
      empty.createEl("p", { text: this.plugin.tr("Go to Settings") });
      return;
    }
    const topSection = content.createDiv("ctdp-top-section");
    const timerContainer = topSection.createDiv("ctdp-timer-container");
    this.renderCircularTimer(timerContainer, 100, "00:00", activeTask.state);
    const controls = topSection.createDiv("ctdp-controls-area");
    this.renderControls(controls, activeTask);
    const statsRow = content.createDiv("ctdp-stats-row");
    const auxStat = statsRow.createDiv("ctdp-stat-group ctdp-side-stat");
    auxStat.createEl("div", { cls: "ctdp-stat-val", text: activeTask.auxChainCount.toString() });
    auxStat.createEl("div", { cls: "ctdp-stat-lbl", text: this.plugin.tr("Bookings") });
    const mainStat = statsRow.createDiv("ctdp-stat-group ctdp-main-stat");
    mainStat.createEl("div", { cls: "ctdp-stat-val", text: activeTask.mainChainCount.toString() });
    mainStat.createEl("div", { cls: "ctdp-stat-lbl", text: this.plugin.tr("Main Chain") });
    const precStat = statsRow.createDiv("ctdp-stat-group ctdp-side-stat");
    const pCount = activeTask.precedents.reduce((a, b) => a + b.usageCount, 0);
    precStat.createEl("div", { cls: "ctdp-stat-val", text: pCount.toString() });
    precStat.createEl("div", { cls: "ctdp-stat-lbl", text: this.plugin.tr("Precedents") });
  }
  renderControls(container, task) {
    if (task.state === "IDLE") {
      const btn = container.createEl("button", { cls: "ctdp-btn-icon ctdp-btn-start" });
      (0, import_obsidian.setIcon)(btn, "alarm-clock");
      btn.setAttribute("aria-label", this.plugin.tr("Book Session"));
      btn.onclick = async () => {
        await this.plugin.bookSession(task.id);
      };
    } else if (task.state === "BOOKED") {
      const cancelBtn = container.createEl("button", { cls: "ctdp-btn-icon ctdp-btn-danger" });
      (0, import_obsidian.setIcon)(cancelBtn, "x");
      cancelBtn.setAttribute("aria-label", this.plugin.tr("Cancel Booking"));
      cancelBtn.onclick = async () => {
        new ConfirmModal(this.plugin.app, this.plugin, this.plugin.tr("Cancel Booking"), this.plugin.tr("Reset Chain?"), this.plugin.tr("Reset All"), async () => {
          await this.plugin.failChain(task.id);
        }).open();
      };
      const skipBtn = container.createEl("button", { cls: "ctdp-btn-icon ctdp-btn-start" });
      (0, import_obsidian.setIcon)(skipBtn, "skip-forward");
      skipBtn.setAttribute("aria-label", this.plugin.tr("Skip Booking"));
      skipBtn.onclick = async () => {
        await this.plugin.startSession(task.id);
      };
    } else if (task.state === "ACTIVE") {
      const stopBtn = container.createEl("button", { cls: "ctdp-btn-icon ctdp-btn-danger" });
      (0, import_obsidian.setIcon)(stopBtn, "skull");
      stopBtn.setAttribute("aria-label", this.plugin.tr("Give Up"));
      stopBtn.onclick = async () => {
        new ConfirmModal(this.plugin.app, this.plugin, this.plugin.tr("Give Up"), this.plugin.tr("Reset Chain?"), this.plugin.tr("Reset All"), async () => {
          await this.plugin.failChain(task.id);
        }).open();
      };
      const pauseBtn = container.createEl("button", { cls: "ctdp-btn-icon ctdp-btn-secondary" });
      (0, import_obsidian.setIcon)(pauseBtn, "pause");
      pauseBtn.setAttribute("aria-label", this.plugin.tr("Pause"));
      pauseBtn.onclick = () => new PrecedentModal(this.plugin.app, this.plugin, task, async () => {
      }).open();
    } else if (task.state === "PAUSED") {
      const resumeBtn = container.createEl("button", { cls: "ctdp-btn-icon ctdp-btn-start" });
      (0, import_obsidian.setIcon)(resumeBtn, "play");
      resumeBtn.setAttribute("aria-label", this.plugin.tr("Resume"));
      resumeBtn.onclick = async () => {
        await this.plugin.resumeSession(task.id);
      };
    }
  }
  renderCircularTimer(container, percent, text, label) {
    container.empty();
    const radius = 110;
    const stroke = 6;
    const normalizedRadius = radius - stroke * 2;
    const circumference = normalizedRadius * 2 * Math.PI;
    const strokeDashoffset = circumference - percent / 100 * circumference;
    let color = "var(--interactive-accent)";
    if (label === "PAUSED")
      color = "var(--text-warning)";
    if (label === "BOOKED")
      color = "var(--text-muted)";
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("height", (radius * 2).toString());
    svg.setAttribute("width", (radius * 2).toString());
    const bgCircle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
    bgCircle.setAttribute("stroke", "var(--background-modifier-border)");
    bgCircle.setAttribute("stroke-width", stroke.toString());
    bgCircle.setAttribute("fill", "transparent");
    bgCircle.setAttribute("r", normalizedRadius.toString());
    bgCircle.setAttribute("cx", radius.toString());
    bgCircle.setAttribute("cy", radius.toString());
    const circle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
    circle.setAttribute("stroke", color);
    circle.setAttribute("stroke-width", stroke.toString());
    circle.setAttribute("stroke-dasharray", `${circumference} ${circumference}`);
    circle.style.strokeDashoffset = strokeDashoffset.toString();
    circle.setAttribute("stroke-linecap", "round");
    circle.setAttribute("fill", "transparent");
    circle.setAttribute("r", normalizedRadius.toString());
    circle.setAttribute("cx", radius.toString());
    circle.setAttribute("cy", radius.toString());
    circle.classList.add("ctdp-progress-ring__circle");
    circle.id = "ctdp-timer-circle-svg";
    svg.appendChild(bgCircle);
    svg.appendChild(circle);
    container.appendChild(svg);
    const contentDiv = container.createDiv("ctdp-timer-content");
    contentDiv.createEl("div", { cls: "ctdp-timer-state", text: this.plugin.tr(label) });
    contentDiv.createEl("div", { cls: "ctdp-timer-time", text, attr: { id: "ctdp-timer-text" } });
  }
  updateTimers() {
    const task = this.getActiveTask();
    if (!task)
      return;
    const now = Date.now();
    let remaining = 0;
    let total = 1;
    if (task.state === "BOOKED" && task.bookingStartTime) {
      const elapsed = now - task.bookingStartTime;
      total = task.bookingDuration * 60 * 1e3;
      remaining = total - elapsed;
    } else if (task.state === "ACTIVE" && task.sessionStartTime) {
      const elapsed = now - task.sessionStartTime;
      total = task.sessionDuration * 60 * 1e3;
      remaining = total - elapsed;
    } else if (task.state === "PAUSED" && task.pauseStartTime && task.activePrecedentId) {
      const p = task.precedents.find((pr) => pr.id === task.activePrecedentId);
      if (p) {
        const elapsed = now - task.pauseStartTime;
        total = p.autoFailMinutes * 60 * 1e3;
        remaining = total - elapsed;
      }
    } else if (task.state === "IDLE") {
      remaining = task.bookingDuration * 60 * 1e3;
      total = remaining;
    }
    if (remaining < 0)
      remaining = 0;
    const percent = remaining / total * 100;
    const timeStr = this.formatTime(remaining);
    const textEl = this.containerEl.querySelector("#ctdp-timer-text");
    if (textEl)
      textEl.textContent = timeStr;
    const circleEl = this.containerEl.querySelector("#ctdp-timer-circle-svg");
    if (circleEl) {
      const radius = 110;
      const stroke = 6;
      const normalizedRadius = radius - stroke * 2;
      const circumference = normalizedRadius * 2 * Math.PI;
      const offset = circumference - percent / 100 * circumference;
      circleEl.style.strokeDashoffset = offset.toString();
    }
  }
  formatTime(ms) {
    const totalSeconds = Math.ceil(ms / 1e3);
    const m = Math.floor(totalSeconds / 60);
    const s = totalSeconds % 60;
    return `${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
  }
};
var ConfirmModal = class extends import_obsidian.Modal {
  constructor(app, plugin, title, message, confirmText, onConfirm) {
    super(app);
    this.plugin = plugin;
    this.title = title;
    this.message = message;
    this.confirmText = confirmText;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("ctdp-modal-center-text");
    contentEl.createEl("h2", { text: this.title });
    contentEl.createEl("p", { text: this.message });
    const btnDiv = contentEl.createDiv("ctdp-modal-center-controls");
    new import_obsidian.ButtonComponent(btnDiv).setButtonText(this.confirmText).setWarning().onClick(() => {
      this.onConfirm();
      this.close();
    });
    new import_obsidian.ButtonComponent(btnDiv).setButtonText(this.plugin.tr("Cancel")).onClick(() => {
      this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var PrecedentEditModal = class extends import_obsidian.Modal {
  constructor(app, plugin, task, onSave) {
    super(app);
    this.plugin = plugin;
    this.task = task;
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.plugin.tr("New Exception Rule") });
    const form = contentEl.createDiv("ctdp-form");
    let newName = "";
    let newDesc = "";
    let newTime = "5";
    new import_obsidian.Setting(form).setName(this.plugin.tr("Name")).addText((t2) => t2.setPlaceholder(this.plugin.tr("e.g. Bathroom")).onChange((v) => newName = v));
    new import_obsidian.Setting(form).setName(this.plugin.tr("Reason")).addText((t2) => t2.setPlaceholder(this.plugin.tr("Why?")).onChange((v) => newDesc = v));
    new import_obsidian.Setting(form).setName(this.plugin.tr("Limit (mins)")).addText((t2) => t2.setValue("5").onChange((v) => newTime = v));
    const btnDiv = contentEl.createDiv("ctdp-modal-center-controls");
    new import_obsidian.ButtonComponent(btnDiv).setButtonText(this.plugin.tr("Add Rule")).setCta().onClick(async () => {
      if (!newName) {
        new import_obsidian.Notice(this.plugin.tr("Name required"));
        return;
      }
      const minutes = parseInt(newTime) || 5;
      const p = { id: Date.now().toString(), name: newName, description: newDesc, autoFailMinutes: minutes, usageCount: 0 };
      this.task.precedents.push(p);
      await this.plugin.saveSettings();
      this.close();
      await this.onSave();
    });
    new import_obsidian.ButtonComponent(btnDiv).setButtonText(this.plugin.tr("Cancel")).onClick(() => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};
var TaskModal = class extends import_obsidian.Modal {
  constructor(app, plugin, task, onSubmit) {
    super(app);
    this.plugin = plugin;
    this.task = task;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    var _a, _b, _c, _d;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.task ? this.plugin.tr("Edit Task") : this.plugin.tr("New Task") });
    let name = ((_a = this.task) == null ? void 0 : _a.name) || "";
    let desc = ((_b = this.task) == null ? void 0 : _b.description) || "";
    let sDur = ((_c = this.task) == null ? void 0 : _c.sessionDuration.toString()) || "60";
    let bDur = ((_d = this.task) == null ? void 0 : _d.bookingDuration.toString()) || "15";
    const form = contentEl.createDiv("ctdp-form");
    new import_obsidian.Setting(form).setName(this.plugin.tr("Name")).addText((text) => text.setValue(name).onChange((v) => name = v));
    new import_obsidian.Setting(form).setName(this.plugin.tr("Description")).addText((text) => text.setValue(desc).onChange((v) => desc = v));
    new import_obsidian.Setting(form).setName(this.plugin.tr("Session Duration")).addText((text) => text.setValue(sDur).onChange((v) => sDur = v));
    new import_obsidian.Setting(form).setName(this.plugin.tr("Booking Duration")).addText((text) => text.setValue(bDur).onChange((v) => bDur = v));
    if (this.task) {
      contentEl.createEl("h3", { text: this.plugin.tr("Manage Exceptions"), attr: { style: "margin-top: 20px; border-bottom: 1px solid var(--background-modifier-border);" } });
      const pList = contentEl.createDiv("ctdp-precedent-list");
      this.renderPrecedents(pList);
      const addPBtn = contentEl.createDiv({ cls: "ctdp-modal-center-controls", attr: { style: "margin-top: 10px;" } });
      new import_obsidian.ButtonComponent(addPBtn).setButtonText("+ " + this.plugin.tr("Add Rule")).onClick(() => {
        new PrecedentEditModal(this.plugin.app, this.plugin, this.task, async () => {
          pList.empty();
          this.renderPrecedents(pList);
        }).open();
      });
    }
    const btnDiv = contentEl.createDiv("ctdp-modal-center-controls");
    btnDiv.style.marginTop = "30px";
    new import_obsidian.ButtonComponent(btnDiv).setButtonText(this.plugin.tr("Save")).setCta().onClick(async () => {
      if (!name) {
        new import_obsidian.Notice(this.plugin.tr("Name required"));
        return;
      }
      const sessionDur = parseInt(sDur);
      const bookingDur = parseInt(bDur);
      const validSessionDur = isNaN(sessionDur) ? 60 : sessionDur;
      const validBookingDur = isNaN(bookingDur) ? 15 : bookingDur;
      if (this.task) {
        this.task.name = name;
        this.task.description = desc;
        this.task.sessionDuration = validSessionDur;
        this.task.bookingDuration = validBookingDur;
      } else {
        const newTask = {
          id: Date.now().toString(),
          name,
          description: desc,
          sessionDuration: validSessionDur,
          bookingDuration: validBookingDur,
          state: "IDLE",
          mainChainCount: 0,
          auxChainCount: 0,
          bookingStartTime: null,
          sessionStartTime: null,
          pauseStartTime: null,
          activePrecedentId: null,
          precedents: [],
          logBookingStartTime: null,
          logPrecedents: []
        };
        if (!this.plugin.settings.tasks)
          this.plugin.settings.tasks = [];
        this.plugin.settings.tasks.push(newTask);
        this.plugin.settings.activeTaskId = newTask.id;
      }
      await this.plugin.saveSettings();
      this.close();
      await this.onSubmit();
    });
  }
  renderPrecedents(container) {
    if (!this.task || this.task.precedents.length === 0) {
      container.createEl("div", { text: this.plugin.tr("No exceptions defined"), attr: { style: "padding: 10px; color: var(--text-muted); text-align: center;" } });
      return;
    }
    this.task.precedents.forEach((p, idx) => {
      const row = container.createDiv("ctdp-precedent-row");
      const details = row.createDiv("ctdp-precedent-details");
      details.createDiv({ cls: "ctdp-precedent-row-name", text: p.name });
      details.createDiv({ cls: "ctdp-precedent-row-meta", text: `${p.autoFailMinutes}m limit | Used: ${p.usageCount}` });
      const delBtn = row.createEl("button", { cls: "ctdp-icon-action ctdp-icon-delete" });
      (0, import_obsidian.setIcon)(delBtn, "trash");
      delBtn.setAttribute("aria-label", this.plugin.tr("Delete rule"));
      delBtn.onclick = async () => {
        new ConfirmModal(this.plugin.app, this.plugin, this.plugin.tr("Delete rule"), `${this.plugin.tr("Delete rule")} "${p.name}"?`, this.plugin.tr("Delete"), async () => {
          this.task.precedents.splice(idx, 1);
          await this.plugin.saveSettings();
          container.empty();
          this.renderPrecedents(container);
        }).open();
      };
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var PrecedentModal = class extends import_obsidian.Modal {
  constructor(app, plugin, task, onSubmit) {
    super(app);
    this.plugin = plugin;
    this.task = task;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.plugin.tr("Interrupt Session") });
    contentEl.createEl("p", { text: this.plugin.tr("Select Exception") });
    const list = contentEl.createDiv("ctdp-precedent-selector");
    this.task.precedents.forEach((p) => {
      const item = list.createDiv("ctdp-precedent-item");
      item.createEl("div", { cls: "ctdp-precedent-name", text: p.name });
      item.createEl("div", { cls: "ctdp-precedent-meta", text: `${p.autoFailMinutes}m limit | Used: ${p.usageCount}` });
      item.onclick = async () => {
        await this.plugin.pauseSession(this.task.id, p.id);
        this.close();
        await this.onSubmit();
      };
    });
    contentEl.createEl("h3", { text: this.plugin.tr("New Exception Rule"), attr: { style: "margin-top: 20px;" } });
    const form = contentEl.createDiv("ctdp-form");
    let newName = "";
    let newDesc = "";
    let newTime = "5";
    new import_obsidian.Setting(form).setName(this.plugin.tr("Name")).addText((t2) => t2.setPlaceholder(this.plugin.tr("e.g. Bathroom")).onChange((v) => newName = v));
    new import_obsidian.Setting(form).setName(this.plugin.tr("Reason")).addText((t2) => t2.setPlaceholder(this.plugin.tr("Why?")).onChange((v) => newDesc = v));
    new import_obsidian.Setting(form).setName(this.plugin.tr("Limit (mins)")).addText((t2) => t2.setValue("5").onChange((v) => newTime = v));
    const btnDiv = contentEl.createDiv("ctdp-modal-center-controls");
    new import_obsidian.ButtonComponent(btnDiv).setButtonText(this.plugin.tr("Create & Use")).setCta().onClick(async () => {
      if (!newName) {
        new import_obsidian.Notice(this.plugin.tr("Name required"));
        return;
      }
      const minutes = parseInt(newTime) || 5;
      const p = { id: Date.now().toString(), name: newName, description: newDesc, autoFailMinutes: minutes, usageCount: 0 };
      this.task.precedents.push(p);
      await this.plugin.saveSettings();
      await this.plugin.pauseSession(this.task.id, p.id);
      this.close();
      await this.onSubmit();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var CTDPSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const taskHeaderContainer = containerEl.createDiv("ctdp-setting-header-container");
    taskHeaderContainer.createEl("h2", { text: this.plugin.tr("Task Chains"), cls: "ctdp-setting-header-text" });
    new import_obsidian.ButtonComponent(taskHeaderContainer).setButtonText("+ " + this.plugin.tr("New Task")).setCta().onClick(() => {
      new TaskModal(this.plugin.app, this.plugin, null, async () => {
        this.display();
        this.plugin.refreshView();
      }).open();
    });
    const taskList = containerEl.createDiv("ctdp-task-list");
    this.plugin.settings.tasks.forEach((task) => {
      const item = taskList.createDiv("ctdp-task-item");
      const main = item.createDiv("ctdp-task-main");
      const headerRow = main.createDiv("ctdp-task-header-row");
      headerRow.createSpan({ cls: "ctdp-task-name", text: task.name });
      if (task.description)
        headerRow.createSpan({ cls: "ctdp-task-desc", text: task.description });
      main.createEl("div", {
        cls: "ctdp-task-stats",
        text: `${this.plugin.tr("Main Chain")}: ${task.mainChainCount} \u2022 ${this.plugin.tr("Bookings")}: ${task.auxChainCount} \u2022 ${this.plugin.tr("Exceptions")}: ${task.precedents.length}`
      });
      const actions = item.createDiv("ctdp-task-actions");
      const editBtn = actions.createEl("button", { cls: "ctdp-icon-action" });
      (0, import_obsidian.setIcon)(editBtn, "pencil");
      editBtn.setAttribute("aria-label", this.plugin.tr("Edit Task"));
      editBtn.onclick = () => {
        new TaskModal(this.plugin.app, this.plugin, task, async () => {
          this.display();
          this.plugin.refreshView();
        }).open();
      };
      const delBtn = actions.createEl("button", { cls: "ctdp-icon-action ctdp-icon-delete" });
      (0, import_obsidian.setIcon)(delBtn, "trash");
      delBtn.setAttribute("aria-label", this.plugin.tr("Delete Task"));
      delBtn.onclick = () => {
        new ConfirmModal(this.plugin.app, this.plugin, this.plugin.tr("Delete Task"), `${this.plugin.tr("Delete")} "${task.name}"?`, this.plugin.tr("Delete"), async () => {
          this.plugin.settings.tasks = this.plugin.settings.tasks.filter((t2) => t2.id !== task.id);
          if (this.plugin.settings.activeTaskId === task.id) {
            this.plugin.settings.activeTaskId = this.plugin.settings.tasks.length > 0 ? this.plugin.settings.tasks[0].id : null;
          }
          await this.plugin.saveSettings();
          this.display();
          this.plugin.refreshView();
        }).open();
      };
    });
    const generalHeaderContainer = containerEl.createDiv("ctdp-setting-header-container");
    generalHeaderContainer.style.marginTop = "30px";
    generalHeaderContainer.createEl("h2", { text: this.plugin.tr("General"), cls: "ctdp-setting-header-text" });
    new import_obsidian.Setting(containerEl).setName(this.plugin.tr("Language")).addDropdown((d) => d.addOption("system", this.plugin.tr("System Default")).addOption("en", "English").addOption("zh", "\u7B80\u4F53\u4E2D\u6587").setValue(this.plugin.settings.language).onChange(async (v) => {
      this.plugin.settings.language = v;
      await this.plugin.saveSettings();
      this.display();
      this.plugin.refreshView();
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.tr("Enable System Notifications")).setDesc(this.plugin.tr("Notifications Desc")).addToggle((t2) => t2.setValue(this.plugin.settings.enableNotifications).onChange(async (v) => {
      this.plugin.settings.enableNotifications = v;
      await this.plugin.saveSettings();
      if (v && Notification.permission !== "granted")
        Notification.requestPermission();
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.tr("Show Timer in Status Bar")).addToggle((t2) => t2.setValue(this.plugin.settings.enableStatusBarTimer).onChange(async (v) => {
      this.plugin.settings.enableStatusBarTimer = v;
      await this.plugin.saveSettings();
      if (!v && this.plugin.statusBarItem)
        this.plugin.statusBarItem.setText("");
    }));
    const loggingHeaderContainer = containerEl.createDiv("ctdp-setting-header-container");
    loggingHeaderContainer.style.marginTop = "30px";
    loggingHeaderContainer.createEl("h2", { text: this.plugin.tr("Daily Logging"), cls: "ctdp-setting-header-text" });
    new import_obsidian.ButtonComponent(loggingHeaderContainer).setButtonText(this.plugin.tr("Auto-detect")).onClick(async () => {
      try {
        const dailyNotesPlugin = this.plugin.app.internalPlugins.getPluginById("daily-notes");
        if (dailyNotesPlugin && dailyNotesPlugin.instance && dailyNotesPlugin.instance.options) {
          this.plugin.settings.dailyLogFormat = dailyNotesPlugin.instance.options.format || "YYYY-MM-DD";
          this.plugin.settings.dailyLogFolder = dailyNotesPlugin.instance.options.folder || "";
          await this.plugin.saveSettings();
          this.display();
          new import_obsidian.Notice(this.plugin.tr("Settings Updated"));
        } else {
          new import_obsidian.Notice(this.plugin.tr("Daily Notes plugin not found or not configured"));
        }
      } catch (e) {
        new import_obsidian.Notice("Error detecting settings");
      }
    });
    new import_obsidian.Setting(containerEl).setName(this.plugin.tr("Date Format")).setDesc(this.plugin.tr("Format Desc")).addText((t2) => t2.setValue(this.plugin.settings.dailyLogFormat).onChange(async (v) => {
      this.plugin.settings.dailyLogFormat = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.tr("Daily Note Folder")).setDesc(this.plugin.tr("Folder Desc")).addText((t2) => t2.setValue(this.plugin.settings.dailyLogFolder).onChange(async (v) => {
      this.plugin.settings.dailyLogFolder = v;
      await this.plugin.saveSettings();
    }));
    const dangerHeaderContainer = containerEl.createDiv("ctdp-setting-header-container");
    dangerHeaderContainer.style.marginTop = "30px";
    dangerHeaderContainer.createEl("h2", { text: this.plugin.tr("Danger Zone"), cls: "ctdp-setting-header-text" });
    dangerHeaderContainer.style.color = "var(--text-error)";
    new import_obsidian.Setting(containerEl).setName(this.plugin.tr("Reset All Settings")).setDesc(this.plugin.tr("Reset Desc")).addButton((b) => b.setButtonText(this.plugin.tr("Reset")).setWarning().onClick(async () => {
      new ConfirmModal(this.plugin.app, this.plugin, this.plugin.tr("Reset All Settings"), this.plugin.tr("Reset Confirm Body"), this.plugin.tr("Reset"), async () => {
        this.plugin.settings = Object.assign({}, DEFAULT_SETTINGS);
        this.plugin.settings.tasks = [];
        await this.plugin.saveSettings();
        this.display();
        this.plugin.refreshView();
        new import_obsidian.Notice("Settings Reset");
      }).open();
    }));
  }
};
